### ISSUE TITLE
Phone field error when empty

### ISSUE THREAD

**Issue by lukeyouell** [barrelstrength/craft-sprout-fields#39]
When saving an entry with an empty phone field I'm seeing the following error:

```
Method barrelstrength\sproutbase\models\sproutfields\Phone::__toString() must return a string value
```

**Comment by BenParizek** [comment]
@lukeyouell Can you confirm you're updated to the latest v3.0.3?

Sounds similar to #38 which we pushed a fix for recently in v3.0.3.

**Comment by lukeyouell** [comment]
@BenParizek I can confirm the version I'm using is 3.0.3

Switching `return $this->international;` to `return (string)$this->international;` did the trick

**Comment by BenParizek** [comment]
@lukeyouell Thanks. We'll look into getting that fixed permanently.

**Comment by lukeyouell** [comment]
Cheers!

**Comment by BenParizek** [comment]
@andrelopez I think this is due to a bug in Craft and how dependencies are getting updated. This bug was resolved but the code Luke updated above is from an older version of Sprout Base. I've opened a ticket here and we'll try to resolve after we get an answer. This is happening with Sprout Reports and Sprout Base too.

https://github.com/craftcms/cms/issues/2560
